import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Creat Ad",
  description: "Generated by create next app",
};

export default function CreateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div>
     {children}
   </div>
  );
}
