import type { Metadata } from "next";
import NavBar from "@/components/navBar";
import "./globals.css";




export const metadata: Metadata = {
  title: {
    default:"home",
    template: "test api Route | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full p-5 md:p-10">
          <NavBar/>
           {children}
        </div>
       
      </body>
    </html>
  );
}
