import { Metadata } from "next";
import Sleep from "@/lib/helpers/Sleep";
import PostClient from "@/components/Postclient";

export const metadata: Metadata = {
  title: "Post",
  description: "Generated by create next app",
};

export interface PostT {
  id: string;
  userId: number;
  title: string;
  body: string;
}

const Post = async () => {
  
  await Sleep(2000);

  // const res = await fetch("http://localhost:3000/api/post", {
  //   cache: "no-store",
  // });
const res = await fetch("/api/post", { cache: "no-store" });


  const posts: PostT[] = await res.json();

  return <PostClient posts={posts} />;
};

export default Post;